// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGugBtTVST6nLcGjp3Ff-3wJhCoZqCvM',
    appId: '1:619871612553:web:ff6cf59f6f42d9965da058',
    messagingSenderId: '619871612553',
    projectId: 'fleet-e95aa',
    authDomain: 'fleet-e95aa.firebaseapp.com',
    storageBucket: 'fleet-e95aa.appspot.com',
    measurementId: 'G-20MJK1G4S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Zdc6fm7wEMZjFEX9b8PhWVBNfa3ZO1c',
    appId: '1:619871612553:android:a2ee96c85d2ab6c65da058',
    messagingSenderId: '619871612553',
    projectId: 'fleet-e95aa',
    storageBucket: 'fleet-e95aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavilf5YG3jQa_5-r_t71DBmFXWjLwaWo',
    appId: '1:619871612553:ios:debd285aa0f0fb1f5da058',
    messagingSenderId: '619871612553',
    projectId: 'fleet-e95aa',
    storageBucket: 'fleet-e95aa.appspot.com',
    iosBundleId: 'com.example.fleetManagementSystem',
  );
}
